---
- name: primer playbook 
  hosts: storage
  remote_user: l10u
  become: true
  tasks: 
    - name: Instalr vim
      apt: name=vim state=latest
    - include: instalar_apache2.yaml

- name: segundo play
  include: segundo_play.yaml
