---
- name: crear fichero usando variables
  hosts: localhost
  connection: local
  become: True
  vars: 
   - miip: "1.2.3.4"
   - milista: ["apache2","mariadb","php5"]
   - milita_larga:
     - ameche2
     - mariadb
     - php5
   - midic: {web: "apache2", db: "mariabd", script: "php5"}
   - midic_largo:
     - web: apache2
     - db: mariadb
     - script: php5 
   - mitexto: | 
        primera linea
        segunda linea
        tercera linea
   - milinealarga: > 
        primera linea okoks
        segunda linea smnlmslmlm
        tercera y fin 
  tasks:
    - debug: var=miip
    - debug: var=milista
    - debug: var=milita_larga
    - debug: var=midic_largo
    - debug: var=mitexto
    - debug: var=milinealarga